[metadata]
name = onsrap
description = A simple Pipeline orchestration package.
version = 0.1.1
author = ONSDigital
platforms = win32
classifiers =
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Programming Language :: Python :: 3.13
    Programming Language :: Python :: 3.14

[options]
packages = find:
python_requires = >=3.10
zip_safe = no
install_requires =
    pyyaml

[options.packages.find]
include =
    onsrap*

[options.package_data]
onsrap =
    py.typed

[options.extras_require]
dev =
    bandit[toml]
    coverage
    pytest-cov
    detect-secrets==1.0.3
    mypy
    myst-parser
    pre-commit
    pytest
    python-dotenv
    ruff
    Sphinx
    toml
    types-PyYAML